name: Build and Push Docker Image
on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
  repository_dispatch:
    types: [upstream-changed]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build and Push on ${{ matrix.platform }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm/v7, windows/amd64]
    steps:
      - name: Display target platform
        run: echo "Building for target platform ${{ matrix.platform }}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Dockerfile
        id: dockerfile
        run: echo "::set-output name=file::$(if [[ "${{ matrix.platform }}" == "windows/amd64" ]]; then echo Dockerfile.windows; else echo Dockerfile.linux; fi)"

      - name: Get lowercase repository name
        id: repo_name
        run: echo "::set-output name=repo::$(echo ${{ github.repository }} | awk '{print tolower($0)}')"

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: ./scripts/build.sh ${{ steps.dockerfile.outputs.file }} ${{ github.sha }} ${{ steps.repo_name.outputs.repo }} ${{ matrix.platform }}

      - name: Test Docker image
        run: ./scripts/test.sh ${{ github.sha }} ${{ steps.repo_name.outputs.repo }} ${{ matrix.platform }}

      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ steps.repo_name.outputs.repo }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.x,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=edge

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ${{ steps.dockerfile.outputs.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}
